In [26]:
#Series vaneko euta line ko output and dataframe vaneko whole table

In [27]:
import numpy as np
import pandas as pd
newsheet=pd.DataFrame(np.random.randint(1,100,100).reshape(50,2))
newsheet.head()

    0   1
0  88  18
1  81  37
2  25  21
3  93  15
4  41  36

In [28]:
newsheet.describe().head()

               0          1
count  50.000000  50.000000
mean   51.960000  41.280000
std    27.698051  27.438272
min     3.000000   4.000000
25%    31.250000  17.250000

In [29]:
#Changing value
newsheet[0][0]=90
newsheet1=newsheet.head()
newsheet1

    0   1
0  90  18
1  81  37
2  25  21
3  93  15
4  41  36

In [30]:
#changing the data into numpy array
newsheet.to_numpy()

array([[90, 18],
       [81, 37],
       [25, 21],
       [93, 15],
       [41, 36],
       [97,  6],
       [71, 27],
       [22, 48],
       [84, 86],
       [53, 12],
       [83, 22],
       [ 8, 65],
       [55, 94],
       [29,  8],
       [40, 41],
       [90, 60],
       [31, 17],
       [75, 16],
       [32, 22],
       [91, 56],
       [ 5, 28],
       [77,  4],
       [ 3, 53],
       [44, 92],
       [62,  8],
       [11, 44],
       [43, 84],
       [46, 73],
       [76, 52],
       [44, 72],
       [55, 77],
       [33, 86],
       [48, 45],
       [37, 57],
       [ 9, 20],
       [30, 11],
       [58, 27],
       [98, 45],
       [89, 35],
       [66, 13],
       [70, 28],
       [43, 89],
       [29,  5],
       [52, 51],
       [86, 38],
       [ 9, 67],
       [ 9, 91],
       [70, 10],
       [60, 35],
       [47, 17]])

In [31]:
#Transposing the data(interchanging rows and column)
newsheet.T

,0,1,2,3,4,5,6,7,8,9,...,40,41,42,43,44,45,46,47,48,49
0,90,81,25,93,41,97,71,22,84,53,...,70,43,29,52,86,9,9,70,60,47
1,18,37,21,15,36,6,27,48,86,12,...,28,89,5,51,38,67,91,10,35,17

In [32]:
#Reversing the data
newsheet.sort_index(axis=1,ascending=False).head()

    1   0
0  18  90
1  37  81
2  21  25
3  15  93
4  36  41

In [33]:
newsheet.head()

    0   1
0  90  18
1  81  37
2  25  21
3  93  15
4  41  36

In [34]:
#for udpdating the value without warning we use loc function
newsheet.loc[0][0]=9
newsheet.head(2)

    0   1
0   9  18
1  81  37

In [35]:
newsheet.loc[0][1]=0
newsheet.head()

    0   1
0   9   0
1  81  37
2  25  21
3  93  15
4  41  36

In [36]:
#Acessing specific rows or column
newsheet=newsheet.loc[[1,2],[0,1]]
newsheet

    0   1
1  81  37
2  25  21

In [37]:
newsheet

    0   1
1  81  37
2  25  21

In [38]:
#for mathematical operations
newsheet.loc[(newsheet[0]>80)]

    0   1
1  81  37

In [39]:
#to print specific value
newsheet.iloc[1,1]

21

In [40]:
newsheet.iloc[[0,1],[0,1]]

    0   1
1  81  37
2  25  21

In [41]:
newsheet.drop([1])

    0   1
2  25  21

In [42]:
newsheet.drop([0],axis=1)

    1
1  37
2  21

In [44]:
#Reseting the index
newsheet.reset_index(drop=True,inplace=True)
newsheet

    0   1
0  81  37
1  25  21

In [45]:
newsheet[0]=None
newsheet

      0   1
0  None  37
1  None  21

In [46]:
newsheet.isnull()

      0      1
0  True  False
1  True  False