In [11]:
import numpy as np
import pandas as pd
df={
    "Name":["Ram","Shyam","Hari"],
    "City":["Bharatpur","Hetauda","Pokhara"],
    "Country":["Nepal","Japan","India"]
}
df=pd.DataFrame(df)
df

    Name       City Country
0    Ram  Bharatpur   Nepal
1  Shyam    Hetauda   Japan
2   Hari    Pokhara   India

In [12]:
df.dropna()

    Name       City Country
0    Ram  Bharatpur   Nepal
1  Shyam    Hetauda   Japan
2   Hari    Pokhara   India

In [13]:
#Adding new columnn
df["Country of Birth"]=["Nepal","Nepal","Nepal"]
df

    Name       City Country Country of Birth
0    Ram  Bharatpur   Nepal            Nepal
1  Shyam    Hetauda   Japan            Nepal
2   Hari    Pokhara   India            Nepal

In [15]:
df["Age"]=[25,26,27]
df

    Name       City Country Country of Birth  Age
0    Ram  Bharatpur   Nepal            Nepal   25
1  Shyam    Hetauda   Japan            Nepal   26
2   Hari    Pokhara   India            Nepal   27

In [16]:
#Modifying existing column
df["Age"]=df["Age"]+2
df

    Name       City Country Country of Birth  Age
0    Ram  Bharatpur   Nepal            Nepal   27
1  Shyam    Hetauda   Japan            Nepal   28
2   Hari    Pokhara   India            Nepal   29

In [21]:
df.drop(["Country of Birth"],axis=1)

    Name       City Country  Age
0    Ram  Bharatpur   Nepal   27
1  Shyam    Hetauda   Japan   28
2   Hari    Pokhara   India   29

In [24]:
df.drop_duplicates(subset=["Country of Birth"])

  Name       City Country Country of Birth  Age
0  Ram  Bharatpur   Nepal            Nepal   27